[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "netbox-ztp"
version = "0.1.0"
description = "Zero Touch Provisioning plugin for NetBox"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "napalm>=4.0.0",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["netbox_ztp*"]

[tool.setuptools.package-data]
netbox_ztp = ["templates/netbox_ztp/*.html"]
